### ISSUE TITLE
Possible bug - slide not working + click on image

### ISSUE THREAD

**Issue by transbetty** [brutaldesign/swipebox#100]
Hello,

I copied the demo to my server and it looks like it's not working properly:
http://transbetty.com/tmp/swipebox//#try 

Scenario 1:
1. open sample gallery
1. try to use slide touch inside viewer
2. doesn't react

Scenario 2:
1. open sample gallery
2. click on a big image
3. loader show and keeps loading forever

This must be server setting related, because I just un-packed the whole download package. Same thing tested on project site http://brutaldesign.github.io/swipebox/#try  prodices no bugs.

Any advice? Thanks, B

**Comment by haroon-sajjad** [comment]
Hi, thank you for very useful and great plugin. 

I have 1.2.9 installed and facing a very weird problem. On full screen popup, navigating to second slide stayed in loading until I move forward and complete the cycle. It worked fine after completing the cycle. I am sure there will be some solution for that. Thanks :)
