### ISSUE TITLE
Get title from somewhere else. 

### ISSUE THREAD

**Issue by rgfx** [brutaldesign/swipebox#154]
Wordpress dropped titles from links, few articles on why title on links is not a good idea. Wondering if I can make swipebox pull from alt text on img.

Tried.

```
if ( $( this ).attr( 'alt' ) ) {
    title = $( this ).attr( 'alt' );
}
```

Didn't work.

**Comment by zuhloobie** [comment]
Hello from 2016 and thanks, this helped me!
