### ISSUE TITLE
youtube video with rel=0

### ISSUE THREAD

**Issue by joubertredrat** [brutaldesign/swipebox#184]
Hi guys,

I liked this project a lot and I'm using in my new project but I have one question.
Youtube videos works normally, but when I put a link with rel=0, this param is removed on embed.

Then, is possible to have a param to set if video have rel or not? If is possible, I can to fork here, modify, test and push request.

**Comment by Guillom** [comment]
Hi,

Add param in the getVideo function.
```
...if (youtubeUrl) {
iframe = '<iframe width="480" height="360" src="//www.youtube.com/embed/' + youtubeUrl[1] + '?fs=1&autohide=1&autoplay=0&rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>'
} else if (vimeoUrl)...
```

**Comment by kidkaos77** [comment]
I tried Guillom's code and couldn't get it to work. 

My work-around is to add "rel=0&" to the <iframe width="560" height="315" src="//'+t[1]+"/embed/"+t[2]+"?"+n+'" frameborder="0" allowfullscreen> in the easy-swipebox/public/js/jquery.swipebox.min.js file.

It should look like this afterwords: <iframe width="560" height="315" src="//'+t[1]+"/embed/"+t[2]+"?rel=0&"+n+'" frameborder="0" allowfullscreen>
