### ISSUE TITLE
PDF/iframe Support?

### ISSUE THREAD

**Issue by andrews05** [brutaldesign/swipebox#214]
I'm trying to move from fancybox to another lightbox and I'm really liking swipebox but I need to be able to load PDFs in the lightbox. Fancybox allows this by setting a data attribute on the link telling it to use an iframe. Any chance a similar ability could be added to swipe box?

**Comment by andrews05** [comment]
To answer my own question, it appears you can make swipbox use an iframe this by adding "swipboxvideo=1" to the href.

**Comment by animaux** [comment]
Some documentation on this would be nice, though :)
