### ISSUE TITLE
Perfect this swipebox!!!

### ISSUE THREAD

**Issue by bdadev** [brutaldesign/swipebox#23]
Very good plugin, works perfectly!

I wonder if he supports putting the count of photos in the gallery, for example: Photo 1 of 367

Is that possible?

Thank you!

**Comment by 1ApSH** [comment]
/**
			 * Set link title attribute as caption
			 */
			setTitle : function ( index ) {
				var title = null;

				$( '#swipebox-title' ).empty();

				if ( elements[ index ] !== undefined ) {
					title = elements[ index ].title;
				}

				if ( title ) {
					$( '#swipebox-top-bar' ).show();
					$( '#swipebox-title' ).append( title );
				} else {
					$( '#swipebox-top-bar' ).hide();
				}
				$('#swipebox-count').text((index+1) + '/' + elements.length);
			},

			html = '<div id="swipebox-overlay">\
					<div id="swipebox-container">\
						<div id="swipebox-slider"></div>\
						<div id="swipebox-top-bar">\
							<div id="swipebox-title"></div>\
						</div>\
						<div id="swipebox-bottom-bar">\
							<div id="swipebox-arrows">\
								<a id="swipebox-prev"></a>\
									<span id="swipebox-count"></span>\
								<a id="swipebox-next"></a>\
							</div>\
						</div>\
						<a id="swipebox-close"></a>\
					</div>\
			</div>';
Work Great thx!

**Comment by 1ApSH** [comment]
Plz Help insert mail form !!
