### ISSUE TITLE
close gallery with click on the black background (#swipebox-overlay)

### ISSUE THREAD

**Issue by mcxnet** [brutaldesign/swipebox#238]
Hello,
is it possibile close the gallery when the user click on the black background (#swipebox-overlay)?
Thanks.

**Comment by webprom** [comment]
// addition for swipebox, closing img on click on bg
    jQuery(function(){
      jQuery(document.body)
          .on('click touchend','#swipebox-slider .current img', function(e){
              return false;
          })
          .on('click touchend','#swipebox-slider .current', function(e){
              jQuery('#swipebox-close').trigger('click');
	 });
   });

**Comment by OlegZavrazhin** [comment]
@webprom it doesn't work on mobile browsers

**Comment by webprom** [comment]
@OlegZavrazhin yes, mobile browser has X to close, check here for example http://www.web-design.co.il/project/vintage-fashion-shop/

**Comment by OlegZavrazhin** [comment]
@webprom it's not exactly what I was looking for

**Comment by thebestgin** [comment]
Don't work on Notebook-Touch.
