### ISSUE TITLE
close button not working

### ISSUE THREAD

**Issue by cafecatKate2015** [brutaldesign/swipebox#241]
hi,
i embedded swipebox into my website. everything works fine except the close button. Somehow, the close button is not reacting when mouse hover and click. I am really new to JS. Could you take a look on my code and advise? Thanks a lot!

http://katehsu.com/swipebox/project_DS.html
swipebox is used for the gallery on the very bottom of page. 

Kate

**Comment by cafecatKate2015** [comment]
I just found that my z-index is not set right. the close button is covered by my main main. The close button works fine after i changed the z-index.

**Comment by michelkeyaerts** [comment]
I have the same issue. How did you fix it?

**Comment by cafecatKate2015** [comment]
hi, there,
It turns out that i have another layer on top of the close button. Check your z-index see if changing z-index can fix it. :)

Best Regards,
Kate Hsu

Date: Wed, 14 Oct 2015 13:22:12 -0700
