### ISSUE TITLE
Error with Right-to-Left languages (Hebrew/Arabic)

### ISSUE THREAD

**Issue by avivhu** [brutaldesign/swipebox#247]
My page is in Hebrew. I can only see the first image. The problem is fixed if I set the interface language in Wordpress to English. I would appreciate any help!

http://52.28.52.53/?page_id=7

**Comment by saqibsarwar** [comment]
In my experience I have fixed the swipebox in RTL using following css

```
html.swipebox-html {
overflow: hidden !important;
}

html.swipebox-html #swipebox-overlay{
direction: ltr;
}
```

**Comment by ziga-miklic** [comment]
@saqibsarwar thank you! Your fix works great :)
