### ISSUE TITLE
Webpack black screen

### ISSUE THREAD

**Issue by justijndepover** [brutaldesign/swipebox#325]
I'm using webpack to bundle all my css / js files. 
I have installed swipebox with `npm install swipebox` and initialised it like so:
```
import 'swipebox/src/css/swipebox.css';
import swipebox from 'swipebox';
$( '.swipebox' ).swipebox();
```

Now whenever i click anywhere on the screen the swipebox modal appears but nothing is in it. So basically i get a black screen with a closing button (which doesn't work).

I don't have any errors in my console or terminal (from compiling with webpack). What am i doing wrong?

**Comment by comi91** [comment]
Same here, does someone has some feedback on this?

**Comment by jasonrhaddix** [comment]
I'm getting the same issue. Installed via NPM, but initialized it per the Basic Usage instructions.

**Comment by kirbyyardley** [comment]
I'm having the same issue.

**Comment by Floooorian** [comment]
I had the same problem but i got it to work with an older jQuery version.
- jQuery 3+ is not working (Black Screen with a not working close button)
- jQuery 2+ works fine

**Comment by kirbyyardley** [comment]
Thanks @Floooorian. That worked for me.

**Comment by mfg92** [comment]
jQuery 3.+ works if you use it together with the [1.4 jQuery migrate plugin](http://jquery.com/download/#jquery-migrate-plugin). It must be included directly after jQuery.

**Comment by daerentis** [comment]
I found this fork, where the jQuery 3+ Problem has been fixed:
https://github.com/mho79/swipebox

**Comment by safiullahsarhandi** [comment]
> I had the same problem but i got it to work with an older jQuery version.
> 
> * jQuery 3+ is not working (Black Screen with a not working close button)
> * jQuery 2+ works fine

you are the one who saved my time really <3
