### ISSUE TITLE
Click event on close button bubbles to underlying div on touch devices

### ISSUE THREAD

**Issue by powerslave** [brutaldesign/swipebox#343]
On mobile / touch, the click event from the lightbox close button (the top-right corner X) bubbles down to the underlying content, behind the overlay div. If a button, or click-sensitive element happens to be below the X, lighbox overlay cannot be closed without "clicking" the underlying element with the same close click.

Discovered this on [the dokuwiki gallery plugin](https://github.com/splitbrain/dokuwiki-plugin-gallery)  which uses swipebox.

Please see issue https://github.com/splitbrain/dokuwiki-plugin-gallery/issues/100 for details and reproduction, 
and the PR with a suggested fix https://github.com/splitbrain/dokuwiki-plugin-gallery/pull/101

**Comment by dylanjameswagner** [comment]
I believe this is the issue addressed in my pending pull request #324 if you can use it to fix your issue, which you may have to do since there is a huge backlog of unaddressed pull requests. :/

**Comment by powerslave** [comment]
@dylanjameswagner: Yes, same issue, same suggested fix, got already merged in [downstream dokuwiki](https://github.com/splitbrain/dokuwiki-plugin-gallery/pull/101).

**Comment by powerslave** [comment]
Close as duplicate of #324.
