### ISSUE TITLE
mp4 video support

### ISSUE THREAD

**Issue by RobertoCMCosta** [brutaldesign/swipebox#41]
Hi,

Is it very difficult to include support for viewing mp4 and other video formats in swipebox? I know I can use youtube/vimeo urls but my client wants to host videos in his own server for legal reasons.
Could you please add this capability?

**Comment by shovanjaya55** [comment]
Hello @itsff 

Are you able to make it support mp4 video support?

Thanks

**Comment by manish-sapkal** [comment]
Is it .mp4 supported?

**Comment by carlosjosedesign** [comment]
This work for me:
in swipebox/jquery.swipebox.min.js
add src.match  into "isVideo:function(src)"  =   src.match(/mp4|wmv|wma|ogv|ogg|flv/)
this new var into "getVideo:function(url)"   = var normalvideoUrl=url.match(/uploads\/([a-zA-Z0-9\-_/.*]+)/)
and a new " else if(normalvideoUrl){ }" [after if(youtubeUrl) and else if(vimeoUrl) ] = 
else if(normalvideoUrl){  iframe= '<video class="wp-video-shortcode" width="560" height="315" preload="metadata" autoplay="autoplay" controls="controls"><source type="video/mp4" src="/wp-content/uploads/'+normalvideoUrl[1]+'"></video>'}

replace "/uploads" and  "/wp-content/" (wordpress default) for each case
 autoplay="autoplay"  is optional

in css file add ",#swipebox-slider .slide .swipebox-video-container .swipebox-video video"  in line "#swipebox-slider .slide .swipebox-video-container .swipebox-video iframe"

**Comment by ceaped** [comment]
Buenos días carlosjosedesign
Yo utilizo : [https://www.mosne.it/playground/swipebox/](url)
El aarchivo "https://www.mosne.it/playground/swipebox/"
Con el me funciona en local los videos de vimeo y YouTube pero no los mp4
Inserto tu código como indicas pero no me funciona.

¿Cómo hago para cargar videos mp4?

Gracias por tu ayuda

**Comment by ghost** [comment]
@carlosjosedesign thaks 
i just added :
 || src.match( /mp4|wmv|wma|ogv|ogg|flv/ )
in :
isVideo : function ( src )
and it worked
