### ISSUE TITLE
RTL unsupport

### ISSUE THREAD

**Issue by OmarBerrayti** [brutaldesign/swipebox#44]
Hi 

I have a css file that contains the direction: rtl; for the body

but one I install the plugin it don't show the next images, it shows just the first one

and once I remove the direction rtl it work !! 

I hope I find a solution for this problem 

Thank You !

**Comment by saqibsarwar** [comment]
In my experience I have fixed the swipebox in RTL using following css

```
html.swipebox-html {
overflow: hidden !important;
}

html.swipebox-html #swipebox-overlay{
direction: ltr;
}
```

**Comment by victoralfonsoperez** [comment]
In fact the issue is related to the animate property used here:
`} else {
                    slider.animate({
                        left: (-index * 100) + '%'
                    });
                }
`
instead of left it should be right for RTL.
