### ISSUE TITLE
Options with slides dynamically loaded

### ISSUE THREAD

**Issue by frinz** [brutaldesign/swipebox#51]
Hi everybody,

Where do I put the options when I load slides dynamically ?

hideBarsDelay : 0, for exemple..

Thanking you in anticipation !

**Comment by pinedziok** [comment]
Hi
I have this:
jQuery.swipebox(
{
  [href: value, title: value],
  [href: value, title: value],
  [href: value, title: value]
}, 
{ hideBarsDelay: 0 }
);

And do not working ;(
My default format is:
jQuery.swipebox(
 [
{href : 'httpx.com/sites/default/files/rozza_viva1.jpg',title : 'title'}, {href : 'http://x.com/sites/default/files/rozza_viva2.jpg',title : 'title'}
]
);

Any help ?
Thanks...

**Comment by Brenderous** [comment]
I'm also having this issue. The solution listed here doesn't work for me. When I tried it I got an "Uncaught SyntaxError: Unexpected token :" error on the first line of the image array.

This is what I have:
```
$.swipebox(
	[
		<?php foreach( $images as $image ): ?>
		{href: '<?=$image['url'];?>', title:'<?php echo $image['alt']; ?>'},
		<?php endforeach; ?>
	],
	{
		initialIndexOnArray: 2
	}
);
```

**Comment by Brenderous** [comment]
I posted my experience with this problem here https://github.com/brutaldesign/swipebox/issues/285. Maybe it'll help someone.
