### ISSUE TITLE
Please add support for YouTube short URL's

### ISSUE THREAD

**Issue by quiptime** [brutaldesign/swipebox#96]
Hi guys,

good work. Many thanks.

At the moment are only URL's supported like this:
http://www.youtube.com/watch?v=XSGBVzeBUbk

Please add support for short URL's like this:
http://youtu.be/XSGBVzeBUbk

Regards

PS
I'm develop a Swipebox module for the CMS Drupal: https://drupal.org/project/dsbox

**Comment by apieceofbart** [comment]
this does not work as expected. You either have to change this line: https://github.com/brutaldesign/swipebox/blob/master/src/js/jquery.swipebox.js#L792 when there's a short video or change the regex
